const cards = [
  {
    image: 'cards/images/floema.jpg',
    site: 'Floema Jewelry',
    contry: 'Italy',
    date: 'July 30, 2021',
    author: 'EMPI',
    authorImage: 'cards/images/EMPI.jpg',
  },
  {
    image: 'cards/images/wanda.jpg',
    site: 'WANDA',
    contry: 'France',
    date: 'July 29, 2021',
    author: 'ENSEMBLE',
    authorImage: 'cards/images/ENSEMBLE.jpg',
  },
  {
    image: 'cards/images/BUT2021.png',
    site: 'Boston University Theatre 2021',
    contry: 'Australia',
    date: 'July 28, 2021',
    author: 'ED.',
    authorImage: 'cards/images/ED.jpg',
  },
  {
    image: 'cards/images/zoox.png',
    site: 'ZOOX',
    contry: 'United States',
    date: 'July 27, 2021',
    author: 'DOGSTUDIO',
    authorImage: 'cards/images/dogstudio.jpg',
  },
  {
    image: 'cards/images/righetti.png',
    site: 'Benjamin Righetti',
    contry: 'France',
    date: 'July 26, 2021',
    author: 'Michael Garcia',
    authorImage: 'cards/images/garcia.png',
  },
  {
    image: 'cards/images/movement.jpg',
    site: 'Seventh Movement',
    contry: 'United States',
    date: 'July 25, 2021',
    author: 'RADCAT',
    authorImage: 'cards/images/radcat.png',
  },
  {
    image: 'cards/images/restore.png',
    site: 'Restore Hope Appeal',
    contry: 'Australia',
    date: 'July 24, 2021',
    author: 'ZN STUDIO',
    authorImage: 'cards/images/zn.png',
  },
  {
    image: 'cards/images/pone.jpg',
    site: 'Pone - LISTEN AND DONATE',
    contry: 'France',
    date: 'July 23, 2021',
    author: 'Merci-Michel',
    authorImage: 'cards/images/merci.jpeg',
  },
  {
    image: 'cards/images/vita.jpg',
    site: 'Vita Architecture',
    contry: 'Netherlands',
    date: 'July 22, 2021',
    author: 'Julie Bonnemoy',
    authorImage: 'cards/images/julie.jpg',
  },
  {
    image: 'cards/images/mama.png',
    site: 'Mama Joyce Peppa Sauce',
    contry: 'United States',
    date: 'July 21, 2021',
    author: 'SAM DAY',
    authorImage: 'cards/images/sam.png',
  },
  {
    image: 'cards/images/bugatti.jpg',
    site: 'Bugatti Smartwatches',
    contry: 'Austria',
    date: 'July 20, 2021',
    author: 'Spatzek Studio',
    authorImage: 'cards/images/spatzek.jpg',
  },
  {
    image: 'cards/images/listen.jpg',
    site: 'Listen To Girls',
    contry: 'India',
    date: 'July 19, 2021',
    author: 'PING-PONG',
    authorImage: 'cards/images/ping-pong.jpg',
  },
];
export default cards;
